version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: default_only_module_positions
  timestamp: 1459722331
layout:
  /header/:
    -
      - position-header
    -
      - system-messages-4590
  /navtop/:
    -
      - 'position-navtop-A 65'
      - 'position-navtop-B 35'
  /navigation/:
    -
      - 'menu-6754 65'
      - 'social-4581 35'
  /slider/:
    -
      - position-slider
  /showcase/:
    -
      - 'position-showcase-A 25'
      - 'position-showcase-B 25'
      - 'position-showcase-C 25'
      - 'position-showcase-D 25'
  /utility/:
    -
      - 'position-utility-A 33.3'
      - 'position-utility-B 33.3'
      - 'position-utility-C 33.3'
  /feature/:
    -
      - position-feature
  /mainabove/:
    -
      - 'position-mainabove-A 50'
      - 'position-mainabove-B 50'
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-sidebar
          -
            - spacer-spacer-1502
      -
        'main 60':
          -
            - position-breadcrumbs
          -
            - system-messages-3340
          -
            - system-content-4336
      -
        'aside 20':
          -
            - position-aside
          -
            - spacer-spacer-2510
  /mainbottom/:
    -
      - 'position-mainbottom-A 50'
      - 'position-mainbottom-B 50'
  /extension/:
    -
      - position-extension-A
  /footer/:
    -
      - 'position-footer-A 25'
      - 'position-footer-B 25'
      - 'position-footer-C 25'
      - 'position-footer-D 25'
  /copyright/:
    -
      - 'position-copyright-A 33.3'
      - 'position-copyright-B 33.3'
      - 'position-copyright-C 33.3'
    -
      - 'copyright-9248 25'
      - 'social-3470 50'
      - 'totop-7007 5'
      - 'branding-8739 20'
  offcanvas:
    -
      - mobile-menu-6557
structure:
  header:
    attributes:
      boxed: ''
  navtop:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: '2'
  slider:
    type: section
    attributes:
      boxed: '2'
      class: ''
      background: ''
  showcase:
    type: section
    attributes:
      boxed: '2'
      class: ''
      background: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  mainabove:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  container-main:
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-navtop-A:
    attributes:
      key: navtop-A
  position-navtop-B:
    attributes:
      key: navtop-B
  position-slider:
    attributes:
      key: slider
  position-showcase-A:
    attributes:
      key: showcase-A
  position-showcase-B:
    attributes:
      key: showcase-B
  position-showcase-C:
    attributes:
      key: showcase-C
  position-showcase-D:
    attributes:
      key: showcase-D
  position-utility-A:
    attributes:
      key: utility-A
  position-utility-B:
    attributes:
      key: utility-B
  position-utility-C:
    attributes:
      key: utility-C
  position-feature:
    attributes:
      key: feature
  position-mainabove-A:
    attributes:
      key: mainabove-A
  position-mainabove-B:
    attributes:
      key: mainabove-B
  position-sidebar:
    attributes:
      key: sidebar
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-aside:
    attributes:
      key: aside
  position-mainbottom-A:
    attributes:
      key: mainbottom-A
  position-mainbottom-B:
    attributes:
      key: mainbottom-B
  position-extension-A:
    attributes:
      key: extension-A
  position-footer-A:
    attributes:
      key: footer-A
  position-footer-B:
    attributes:
      key: footer-B
  position-footer-C:
    attributes:
      key: footer-C
  position-footer-D:
    attributes:
      key: footer-D
  position-copyright-A:
    attributes:
      key: copyright-A
  position-copyright-B:
    attributes:
      key: copyright-B
  position-copyright-C:
    attributes:
      key: copyright-C
